name: Add `orange` label to new issues and PRs
on: [issues, pull_request]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - uses: DataBiosphere/azul-github-labeler-action@v4
      with:
        repo-token: "${{secrets.GITHUB_TOKEN}}"
        label: orange
